# Generated by Django 4.1.7 on 2023-05-09 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id_suggestion', models.AutoField(primary_key=True, serialize=False)),
                ('suggestion', models.CharField(max_length=5000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(default='New', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
