# Generated by Django 4.1.7 on 2023-04-02 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=30)),
                ('group_desc', models.TextField(max_length=400)),
                ('group_photo_profile_link', models.CharField(max_length=150)),
                ('group_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.category')),
                ('group_member', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_desc', models.TextField(max_length=2000)),
                ('post_image_link', models.CharField(max_length=500)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_likes', models.IntegerField(default=0)),
                ('post_user_name', models.CharField(max_length=100, null=True)),
                ('post_group_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
                ('post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goods_id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=70)),
                ('goods_price', models.IntegerField()),
                ('goods_description', models.TextField(max_length=1000)),
                ('goods_image_link', models.CharField(max_length=500)),
                ('goods_region', models.CharField(max_length=70)),
                ('seller_name', models.CharField(max_length=100, null=True)),
                ('goods_group_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
                ('goods_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
