# Generated by Django 4.1.7 on 2023-05-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_goods_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tags_id', models.AutoField(primary_key=True, serialize=False)),
                ('tags_name', models.CharField(max_length=50)),
                ('tags_in_post', models.ManyToManyField(to='group.post')),
            ],
        ),
    ]
