# Generated by Django 4.1.7 on 2023-05-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='tags_in_post',
        ),
        migrations.AddField(
            model_name='post',
            name='post_tags',
            field=models.ManyToManyField(to='group.tags'),
        ),
    ]
