# Generated by Django 4.1.7 on 2023-05-17 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_like_comment'),
        ('group', '0005_group_date_created'),
    ]

    operations = [
    ]
