# Generated by Django 4.1.7 on 2023-05-17 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_remove_tags_tags_in_post_post_post_tags'),
        ('group', '0006_merge_0004_like_comment_0005_group_date_created'),
    ]

    operations = [
    ]
