# Generated by Django 4.1.7 on 2023-04-13 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authuser', '0002_address_is_main'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('resi', models.CharField(max_length=100, null=True)),
                ('progress', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('snap_token', models.CharField(max_length=100, null=True)),
                ('address_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authuser.address')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.goods')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
