# Generated by Django 4.1.7 on 2023-04-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_buy',
            field=models.BooleanField(default=False),
        ),
    ]
