# Generated by Django 4.1.7 on 2023-04-27 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_is_buy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_buy',
        ),
    ]
