# Generated by Django 4.1.7 on 2023-05-21 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0002_complain"),
        ("transaction", "0004_transaction_seller"),
    ]

    operations = []
