# Generated by Django 4.1.7 on 2023-05-21 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_bankaccount_withdrawalhistory'),
        ('transaction', '0005_merge_0002_complain_0004_transaction_seller'),
    ]

    operations = [
    ]
