# Generated by Django 4.1.7 on 2023-05-23 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0006_merge_20230521_1605"),
    ]

    operations = [
        migrations.AddField(
            model_name="complain",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
