# Generated by Django 4.1.7 on 2023-05-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0007_complain_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complain",
            name="complain_text",
            field=models.TextField(max_length=400),
        ),
    ]
