# Generated by Django 4.1.7 on 2023-04-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
