# Generated by Django 4.1.7 on 2023-04-13 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('shopcart', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to='shopcart.cart')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='group.goods')),
            ],
        ),
    ]
